# K8s 클러스터의 lastcup 네임스페이스를 생성하는 매니페스트입니다.
# 매니페스트: K8s 에게 "이걸 만들어줘"라고 적어서 넘기는 주문서

# 모든 K8s YAML 파일에는 apiVersion, kind, metadata 필드가 필수로 들어가야 합니다.
# apiVersion: 기본 v1 API 그룹이다.
# API 그룹: K8s 리소스를 카테고리별로 묶어 놓은 그룹.
apiVersion: v1    # 버전 몇의 양식으로 적었는지 명시 -> v1은 가장 기본 버전
kind: Namespace   # "뭘 만들 것인가?" -> 이 파일로 Namespace를 만들겠다
metadata:         # 이 리소스의 신원 정보
  name: lastcup   # "이 네임스페이스의 이름은 lastcup입니다"
